M48
; DRILL file {KiCad (6.0.11)} date So 05 Mär 2023 15:12:20 CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-05T15:12:20+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X30.51Y-78.197
X36.29Y-78.197
T2
X14.56Y-79.977
X22.56Y-79.977
T3
X4.0Y-4.0
X4.0Y-80.0
X42.0Y-80.0
X65.0Y-37.0
T0
M30
